name: ServiceNow GitHub Actions Demo

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  publish:
    # Purpose of this job is to demonstrate publishing an Application Customization 
    name: Publish from Dev
    runs-on: ubuntu-24.04
    steps:
      - name: ServiceNow CI/CD Publish App
        id: publish_app
        uses: ServiceNow/sncicd-publish-app@2.0.1
        with:
          versionTemplate: 1.1
          versionFormat: template
          incrementBy: 1
          isAppCustomization: true
        env:
          nowUsername: admin
          nowPassword: 7fv$B4ly$NLE
          nowSourceInstance: https://dev213765.service-now.com/
          appSysID: 1628fd5d47a49210a3b3d369316d43f6