name: ServiceNow GitHub Actions Demo

on:
  pull_request:
  push:
    branches:
      - main
env:
    
jobs:
  publish:
    # Purpose of this job is to demonstrate publishing an Application Customization 
    name: Publish from Dev
    runs-on: ubuntu-latest
    steps:
      - name: ServiceNow CI/CD Publish App
        id: publish_app
        uses: ServiceNow/sncicd-publish-app@2.0.1
        with:
          versionTemplate: 1.1
          versionFormat: template
          incrementBy: 1
          isAppCustomization: true
        env:
          nowUsername: ${{ secrets.SN_USERNAME }}
          nowPassword: ${{ secrets.SN_PASSWORD }}
          nowSourceInstance: ${{ secrets.SN_DEV_INSTANCE }}
          appSysID: ${{ secrets.SN_APP_SYSID }}